channels:
- defaults
dependencies:
 - python=3.9
 - pip
 - black
 - pytest
 - numpy
 - scipy
 - pandas
 - matplotlib
 - seaborn
 - pytorch::pytorch
 - pytorch::torchvision
 - tqdm
 - ipykernel
 - pip:
   - pydove
