name:
  cpcn
channels:
- defaults
- conda-forge
dependencies:
 - python=3.9
 - pip
 - black
 - pytest
 - numpy
 - scipy
 - pandas
 - matplotlib
 - seaborn
 - pytorch::pytorch
 - pytorch::torchvision
 - scikit-learn
 - optuna
 - tqdm
 - jupyter
 - ipywidgets
 - pip:
   - pydove
